/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model;


import ch.ffhs.savvy_spring.jooq.model.tables.AppUser;
import ch.ffhs.savvy_spring.jooq.model.tables.Diaryentry;
import ch.ffhs.savvy_spring.jooq.model.tables.Sportstuff;
import ch.ffhs.savvy_spring.jooq.model.tables.Todo;
import ch.ffhs.savvy_spring.jooq.model.tables.Todolist;
import ch.ffhs.savvy_spring.jooq.model.tables.records.AppUserRecord;
import ch.ffhs.savvy_spring.jooq.model.tables.records.DiaryentryRecord;
import ch.ffhs.savvy_spring.jooq.model.tables.records.SportstuffRecord;
import ch.ffhs.savvy_spring.jooq.model.tables.records.TodoRecord;
import ch.ffhs.savvy_spring.jooq.model.tables.records.TodolistRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppUserRecord> APP_USER_EMAIL_KEY = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("app_user_email_key"), new TableField[] { AppUser.APP_USER.EMAIL }, true);
    public static final UniqueKey<AppUserRecord> APP_USER_PKEY = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("app_user_pkey"), new TableField[] { AppUser.APP_USER.ID }, true);
    public static final UniqueKey<AppUserRecord> APP_USER_USERNAME_KEY = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("app_user_username_key"), new TableField[] { AppUser.APP_USER.USERNAME }, true);
    public static final UniqueKey<DiaryentryRecord> DIARYENTRY_PKEY = Internal.createUniqueKey(Diaryentry.DIARYENTRY, DSL.name("diaryentry_pkey"), new TableField[] { Diaryentry.DIARYENTRY.ENTRYID }, true);
    public static final UniqueKey<SportstuffRecord> SPORTSTUFF_PKEY = Internal.createUniqueKey(Sportstuff.SPORTSTUFF, DSL.name("sportstuff_pkey"), new TableField[] { Sportstuff.SPORTSTUFF.ID }, true);
    public static final UniqueKey<TodoRecord> TODO_PKEY1 = Internal.createUniqueKey(Todo.TODO, DSL.name("todo_pkey1"), new TableField[] { Todo.TODO.TODOLIST_ID, Todo.TODO.ID }, true);
    public static final UniqueKey<TodolistRecord> TODO_PKEY = Internal.createUniqueKey(Todolist.TODOLIST, DSL.name("todo_pkey"), new TableField[] { Todolist.TODOLIST.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TodoRecord, TodolistRecord> TODO__FK_TODO_TODOLIST = Internal.createForeignKey(Todo.TODO, DSL.name("fk_todo_todolist"), new TableField[] { Todo.TODO.TODOLIST_ID }, Keys.TODO_PKEY, new TableField[] { Todolist.TODOLIST.ID }, true);
}
