/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model;


import ch.ffhs.savvy_spring.jooq.model.tables.AppUser;
import ch.ffhs.savvy_spring.jooq.model.tables.Diaryentry;
import ch.ffhs.savvy_spring.jooq.model.tables.Sportstuff;
import ch.ffhs.savvy_spring.jooq.model.tables.Todo;
import ch.ffhs.savvy_spring.jooq.model.tables.Todolist;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.diaryentry</code>.
     */
    public static final Diaryentry DIARYENTRY = Diaryentry.DIARYENTRY;

    /**
     * The table <code>public.sportstuff</code>.
     */
    public static final Sportstuff SPORTSTUFF = Sportstuff.SPORTSTUFF;

    /**
     * The table <code>public.todo</code>.
     */
    public static final Todo TODO = Todo.TODO;

    /**
     * The table <code>public.todoList</code>.
     */
    public static final Todolist TODOLIST = Todolist.TODOLIST;
}
