/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model.tables.records;


import ch.ffhs.savvy_spring.jooq.model.tables.Sportstuff;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportstuffRecord extends UpdatableRecordImpl<SportstuffRecord> implements Record5<Integer, String, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sportstuff.id</code>.
     */
    public SportstuffRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sportstuff.text</code>.
     */
    public SportstuffRecord setText(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.text</code>.
     */
    public String getText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.sportstuff.user_id</code>.
     */
    public SportstuffRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.sportstuff.title</code>.
     */
    public SportstuffRecord setTitle(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sportstuff.creation_date</code>.
     */
    public SportstuffRecord setCreationDate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.creation_date</code>.
     */
    public LocalDateTime getCreationDate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sportstuff.SPORTSTUFF.ID;
    }

    @Override
    public Field<String> field2() {
        return Sportstuff.SPORTSTUFF.TEXT;
    }

    @Override
    public Field<Integer> field3() {
        return Sportstuff.SPORTSTUFF.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return Sportstuff.SPORTSTUFF.TITLE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Sportstuff.SPORTSTUFF.CREATION_DATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getText();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public LocalDateTime component5() {
        return getCreationDate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getText();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public LocalDateTime value5() {
        return getCreationDate();
    }

    @Override
    public SportstuffRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SportstuffRecord value2(String value) {
        setText(value);
        return this;
    }

    @Override
    public SportstuffRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public SportstuffRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public SportstuffRecord value5(LocalDateTime value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public SportstuffRecord values(Integer value1, String value2, Integer value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SportstuffRecord
     */
    public SportstuffRecord() {
        super(Sportstuff.SPORTSTUFF);
    }

    /**
     * Create a detached, initialised SportstuffRecord
     */
    public SportstuffRecord(Integer id, String text, Integer userId, String title, LocalDateTime creationDate) {
        super(Sportstuff.SPORTSTUFF);

        setId(id);
        setText(text);
        setUserId(userId);
        setTitle(title);
        setCreationDate(creationDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SportstuffRecord
     */
    public SportstuffRecord(ch.ffhs.savvy_spring.jooq.model.tables.pojos.Sportstuff value) {
        super(Sportstuff.SPORTSTUFF);

        if (value != null) {
            setId(value.getId());
            setText(value.getText());
            setUserId(value.getUserId());
            setTitle(value.getTitle());
            setCreationDate(value.getCreationDate());
            resetChangedOnNotNull();
        }
    }
}
