/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model.tables;


import ch.ffhs.savvy_spring.jooq.model.Keys;
import ch.ffhs.savvy_spring.jooq.model.Public;
import ch.ffhs.savvy_spring.jooq.model.tables.records.TodoRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todo extends TableImpl<TodoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.todo</code>
     */
    public static final Todo TODO = new Todo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TodoRecord> getRecordType() {
        return TodoRecord.class;
    }

    /**
     * The column <code>public.todo.id</code>.
     */
    public final TableField<TodoRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.todo.content</code>.
     */
    public final TableField<TodoRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.todo.todolist_id</code>.
     */
    public final TableField<TodoRecord, Integer> TODOLIST_ID = createField(DSL.name("todolist_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Todo(Name alias, Table<TodoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Todo(Name alias, Table<TodoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.todo</code> table reference
     */
    public Todo(String alias) {
        this(DSL.name(alias), TODO);
    }

    /**
     * Create an aliased <code>public.todo</code> table reference
     */
    public Todo(Name alias) {
        this(alias, TODO);
    }

    /**
     * Create a <code>public.todo</code> table reference
     */
    public Todo() {
        this(DSL.name("todo"), null);
    }

    public <O extends Record> Todo(Table<O> child, ForeignKey<O, TodoRecord> key) {
        super(child, key, TODO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TodoRecord, Integer> getIdentity() {
        return (Identity<TodoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TodoRecord> getPrimaryKey() {
        return Keys.TODO_PKEY1;
    }

    @Override
    public List<ForeignKey<TodoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TODO__FK_TODO_TODOLIST);
    }

    private transient Todolist _todolist;

    /**
     * Get the implicit join path to the <code>public.todoList</code> table.
     */
    public Todolist todolist() {
        if (_todolist == null)
            _todolist = new Todolist(this, Keys.TODO__FK_TODO_TODOLIST);

        return _todolist;
    }

    @Override
    public Todo as(String alias) {
        return new Todo(DSL.name(alias), this);
    }

    @Override
    public Todo as(Name alias) {
        return new Todo(alias, this);
    }

    @Override
    public Todo as(Table<?> alias) {
        return new Todo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(String name) {
        return new Todo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(Name name) {
        return new Todo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(Table<?> name) {
        return new Todo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
