/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy.savvyspring.jooq.tables.records;


import ch.ffhs.savvy.savvyspring.jooq.tables.Todolist;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodolistRecord extends UpdatableRecordImpl<TodolistRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.todoList.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.todoList.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.todoList.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.todoList.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.todoList.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.todoList.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Todolist.TODOLIST.ID;
    }

    @Override
    public Field<String> field2() {
        return Todolist.TODOLIST.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Todolist.TODOLIST.USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public TodolistRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TodolistRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TodolistRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TodolistRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodolistRecord
     */
    public TodolistRecord() {
        super(Todolist.TODOLIST);
    }

    /**
     * Create a detached, initialised TodolistRecord
     */
    public TodolistRecord(Integer id, String name, Integer userId) {
        super(Todolist.TODOLIST);

        setId(id);
        setName(name);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
