/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy.savvyspring.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.todoList_id_seq</code>
     */
    public static final Sequence<Integer> TODOLIST_ID_SEQ = Internal.createSequence("todoList_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
