/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy.savvyspring.jooq;


import ch.ffhs.savvy.savvyspring.jooq.tables.AppUser;
import ch.ffhs.savvy.savvyspring.jooq.tables.Todo;
import ch.ffhs.savvy.savvyspring.jooq.tables.Todolist;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.todo</code>.
     */
    public static final Todo TODO = Todo.TODO;

    /**
     * The table <code>public.todoList</code>.
     */
    public static final Todolist TODOLIST = Todolist.TODOLIST;
}
