/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String username;
    private String email;
    private String password;
    private String role;
    private String status;

    public AppUser() {}

    public AppUser(AppUser value) {
        this.id = value.id;
        this.username = value.username;
        this.email = value.email;
        this.password = value.password;
        this.role = value.role;
        this.status = value.status;
    }

    public AppUser(
        Integer id,
        String username,
        String email,
        String password,
        String role,
        String status
    ) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
        this.status = status;
    }

    /**
     * Getter for <code>public.app_user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.app_user.id</code>.
     */
    public AppUser setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.app_user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.app_user.username</code>.
     */
    public AppUser setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>public.app_user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.app_user.email</code>.
     */
    public AppUser setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.app_user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.app_user.password</code>.
     */
    public AppUser setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.app_user.role</code>.
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>public.app_user.role</code>.
     */
    public AppUser setRole(String role) {
        this.role = role;
        return this;
    }

    /**
     * Getter for <code>public.app_user.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.app_user.status</code>.
     */
    public AppUser setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AppUser other = (AppUser) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppUser (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(role);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
