/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diaryentry implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer entryid;
    private String content;
    private String title;
    private String userId;

    public Diaryentry() {}

    public Diaryentry(Diaryentry value) {
        this.entryid = value.entryid;
        this.content = value.content;
        this.title = value.title;
        this.userId = value.userId;
    }

    public Diaryentry(
        Integer entryid,
        String content,
        String title,
        String userId
    ) {
        this.entryid = entryid;
        this.content = content;
        this.title = title;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.diaryentry.entryid</code>.
     */
    public Integer getEntryid() {
        return this.entryid;
    }

    /**
     * Setter for <code>public.diaryentry.entryid</code>.
     */
    public Diaryentry setEntryid(Integer entryid) {
        this.entryid = entryid;
        return this;
    }

    /**
     * Getter for <code>public.diaryentry.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.diaryentry.content</code>.
     */
    public Diaryentry setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for <code>public.diaryentry.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.diaryentry.title</code>.
     */
    public Diaryentry setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>public.diaryentry.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.diaryentry.user_id</code>.
     */
    public Diaryentry setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Diaryentry other = (Diaryentry) obj;
        if (this.entryid == null) {
            if (other.entryid != null)
                return false;
        }
        else if (!this.entryid.equals(other.entryid))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.entryid == null) ? 0 : this.entryid.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Diaryentry (");

        sb.append(entryid);
        sb.append(", ").append(content);
        sb.append(", ").append(title);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
