/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sportstuff implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String text;
    private Integer userId;
    private String title;
    private LocalDateTime creationDate;

    public Sportstuff() {}

    public Sportstuff(Sportstuff value) {
        this.id = value.id;
        this.text = value.text;
        this.userId = value.userId;
        this.title = value.title;
        this.creationDate = value.creationDate;
    }

    public Sportstuff(
        Integer id,
        String text,
        Integer userId,
        String title,
        LocalDateTime creationDate
    ) {
        this.id = id;
        this.text = text;
        this.userId = userId;
        this.title = title;
        this.creationDate = creationDate;
    }

    /**
     * Getter for <code>public.sportstuff.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.sportstuff.id</code>.
     */
    public Sportstuff setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.text</code>.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Setter for <code>public.sportstuff.text</code>.
     */
    public Sportstuff setText(String text) {
        this.text = text;
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.sportstuff.user_id</code>.
     */
    public Sportstuff setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.sportstuff.title</code>.
     */
    public Sportstuff setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>public.sportstuff.creation_date</code>.
     */
    public LocalDateTime getCreationDate() {
        return this.creationDate;
    }

    /**
     * Setter for <code>public.sportstuff.creation_date</code>.
     */
    public Sportstuff setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sportstuff other = (Sportstuff) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.text == null) {
            if (other.text != null)
                return false;
        }
        else if (!this.text.equals(other.text))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.creationDate == null) {
            if (other.creationDate != null)
                return false;
        }
        else if (!this.creationDate.equals(other.creationDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.text == null) ? 0 : this.text.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.creationDate == null) ? 0 : this.creationDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sportstuff (");

        sb.append(id);
        sb.append(", ").append(text);
        sb.append(", ").append(userId);
        sb.append(", ").append(title);
        sb.append(", ").append(creationDate);

        sb.append(")");
        return sb.toString();
    }
}
