/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todolist implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String userId;

    public Todolist() {}

    public Todolist(Todolist value) {
        this.id = value.id;
        this.name = value.name;
        this.userId = value.userId;
    }

    public Todolist(
        Integer id,
        String name,
        String userId
    ) {
        this.id = id;
        this.name = name;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.todoList.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.todoList.id</code>.
     */
    public Todolist setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.todoList.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.todoList.name</code>.
     */
    public Todolist setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.todoList.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.todoList.user_id</code>.
     */
    public Todolist setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Todolist other = (Todolist) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Todolist (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
