/*
 * This file is generated by jOOQ.
 */
package ch.ffhs.savvy_spring.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String content;
    private Integer todolistId;

    public Todo() {}

    public Todo(Todo value) {
        this.id = value.id;
        this.content = value.content;
        this.todolistId = value.todolistId;
    }

    public Todo(
        Integer id,
        String content,
        Integer todolistId
    ) {
        this.id = id;
        this.content = content;
        this.todolistId = todolistId;
    }

    /**
     * Getter for <code>public.todo.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.todo.id</code>.
     */
    public Todo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.todo.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.todo.content</code>.
     */
    public Todo setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for <code>public.todo.todolist_id</code>.
     */
    public Integer getTodolistId() {
        return this.todolistId;
    }

    /**
     * Setter for <code>public.todo.todolist_id</code>.
     */
    public Todo setTodolistId(Integer todolistId) {
        this.todolistId = todolistId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Todo other = (Todo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.todolistId == null) {
            if (other.todolistId != null)
                return false;
        }
        else if (!this.todolistId.equals(other.todolistId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.todolistId == null) ? 0 : this.todolistId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Todo (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(todolistId);

        sb.append(")");
        return sb.toString();
    }
}
